"""Write evidence-derived ordinary-file collection targets. Does not contact a vehicle."""
from pathlib import Path
import json,hashlib
R=Path(__file__).resolve().parent
inv=json.loads((R/'source_inventory.json').read_text())
def by_suffix(suffix):
 matches=[{'archive':s['name'],'member':m['path'],'sha256':m['sha256'],'bytes':m['bytes']} for s in inv['sources'] for m in s['members'] if m['path'].endswith(suffix)]
 return matches
rows=[]
def add(domain,path,reason,source,known=None,status='known_file_collect_changed_variant',variant='Installed variant matching the user vehicle; retain version and hash.',maximum=536870912):
 rows.append({'domain':domain,'path':path,'reason':reason,'source_evidence':source,'known_sha256':sorted(set(x['sha256'] for x in known or [])),'known_sources':known or [],'required_variant':variant,'status':status,'maximum_bytes':maximum,'operation':{'kind':'ordinary_file_read','follow_device_symlinks':False,'vehicle_network_command':False,'read_only_command': ['adb','exec-out','sh','-c',"cat -- '"+path+"'"] if domain=='Android' else None,'qconn_operation': 'review exact ordinary path before collection; file_open(O_RDONLY); file_stat; accept regular file only; file_read; file_close; no pre-open lstat available' if domain=='QNX' else None}})
producer=by_suffix('/vendor_bin_smartcore_update_client')[0]
for stem in ['udisk_manifest.json','update-swp1.tar.gz','update-swl3.tar.gz','update-swl4.tar.gz','update-swlm.tar.gz','update-swl2.tar.gz']:
 add('Android','/ota_download/'+stem,'Missing real package/manifest bytes can identify payload ownership, part inventory, software version and any production VP/MCU payload. Part names alone do not identify MCU.',[producer,{'local_evidence':'lv_image_inventory.json','member':'sbin/usb_update.sh','image_sha256':'4a0cd3a681364059ace2c857d4d7436e0902660c43601b48d0ef735e86d23680'}],status='conditional_from_producer_code_not_observed_installed',variant='Exact package already present for this vehicle/version; do not trigger download/update or mount.',maximum=2147483648)
for path,suffix,why in [('/vendor/bin/smartcore_update_client','/vendor_bin_smartcore_update_client','Correlate actual package-copy branch with installed updater.'),('/system/bin/smartcore_update_client','/system_bin_smartcore_update_client','Existing second updater path; hash-equal copy adds no new semantics.'),('/vendor/etc/usb_reflash_config.json','/vendor/etc/usb_reflash_config.json','Real config selects ECARX/HIGH/folder/udisk_manifest.json; compare changed variants.'),('/system/etc/usb_reflash_config.json','/system/etc/usb_reflash_config.json','Exact default config path appears in updater at VA0xea35; existence and alias to vendor config remain unproven.')]:
 k=by_suffix(suffix);add('Android',path,why,[producer],k,status='known_file_collect_changed_variant' if k else 'conditional_from_producer_code_not_observed_installed')
for path,why in [('/bin/sc_qnx_vip_proxy','Compare the six finite registered SOME/IP handlers with any changed vehicle variant.'),('/bin/can_driver','Compare generic SPI/CAN resource-manager code; do not open the device node.'),('/bin/SwVersionService','Correlate QNX software-version provider.'),('/etc/sw-version-info.txt','Record actual ES/ER QNX version with files.'),('/vm/images_lv/linux-lv.img','If changed, decode updated Linux LV initramfs offline for updater and log handler paths.')]:
 k=by_suffix('/qnx/files'+path);add('QNX',path,why,k,k)
(R/'collection_targets.json').write_text(json.dumps({'scope':'Cruise-specific evidence-derived additions. Existing files should be hash-skipped. No path scanning, launching firmware/updaters, device reads, replay or control writes. Unknown file absence is a valid result.','targets':rows,'not_collectable_through_current_android_qnx_filesystem': [{'domain':'Linux_LV_initramfs_runtime','path_pattern':'/data/kernellog/vp_*.log','proven_directory':'/data/kernellog','proven_prefix':'vp','evidence':'mcu_log SHA33d91dad416089274af3ec23b4e5b8824b69a5196313b3162c40bdfd65e4fd0b VA400a1c..400a3c passes directory and prefix to logging setup; generated names %s/%s_%d.log. Runtime guest alias into Android/QNX not established.','missing_fact':'Mounted location of LV /dev/block/vdb within an already-running accessible filesystem. No new mount or LV boot is authorized.','prohibited_action':'Do not execute mcu_log: callback400c1c performs mkdir and mount.'}],'missing_fact_without_exact_collectable_path':['Production VP/MCU image corresponding to MCU version20.24.10.23024.41141 and hardware identity of 198.18.34.1:50500.','Wheel-switch receiving ECU handler and downstream cruise request/counter/checksum/eligibility semantics.','Meaning/ownership of swlm/swp1 package segments; names alone are insufficient.'],'excluded':['/dev/can*','/dev/spi*','raw block devices','firmware execution','updater execution','vehicle-network messages']},ensure_ascii=False,indent=2))
print(len(rows),'targets')
