/* SPDX-License-Identifier: GPL-3.0-or-later */
package dezz.status.widget.phone.transport.v2;

import java.util.Objects;

/** Immutable start input.  The switch coordinator, not a route, owns epoch allocation. */
public final class IphoneTransportStartRequest {
    public final BleRouteEpoch epoch;
    /** Android-only address/key used to target the already selected system bond. */
    public final String selectedSystemBondAddress;
    /** Stable random ID generated by Helper; never confused with either platform's peer UUID. */
    public final String helperInstallationId;
    public final boolean radioEnabled;
    public final long monotonicNowMillis;
    public final IphoneAcquisitionModeV2 acquisitionMode;

    public IphoneTransportStartRequest(BleRouteEpoch epoch, String selectedSystemBondAddress,
                                       String helperInstallationId,
                                       boolean radioEnabled, long monotonicNowMillis,
                                       IphoneAcquisitionModeV2 acquisitionMode) {
        this.epoch = Objects.requireNonNull(epoch, "epoch");
        this.selectedSystemBondAddress =
                IphoneBleAdvertisement.normalizePeerId(selectedSystemBondAddress);
        this.helperInstallationId =
                IphoneBleAdvertisement.normalizePeerId(helperInstallationId);
        if (this.selectedSystemBondAddress.isEmpty()) {
            throw new IllegalArgumentException("selectedSystemBondAddress is required");
        }
        if (monotonicNowMillis < 0L) {
            throw new IllegalArgumentException("monotonicNowMillis must be non-negative");
        }
        this.radioEnabled = radioEnabled;
        this.monotonicNowMillis = monotonicNowMillis;
        this.acquisitionMode = Objects.requireNonNull(acquisitionMode, "acquisitionMode");
        // SELECTED_BOND is also the first-bootstrap path. Before H is learned, the adapter still
        // requires one exact bonded facade and an encryption-required Helper proof; an empty H
        // never grants authority by itself.
    }
}
