/* SPDX-License-Identifier: GPL-3.0-or-later */
package dezz.status.widget.launcher;

import androidx.annotation.DrawableRes;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import dezz.status.widget.R;

/** Generated curated Microsoft Fluent UI System Icons 1.1.328 catalog, loaded on demand. */
public final class FluentIconCatalog {
    private static final int ICON_COUNT = 322;

    private FluentIconCatalog() {}

    @NonNull static List<LauncherIconResolver.Preset> presets() {
        return PresetHolder.PRESETS;
    }

    @DrawableRes static int resource(@Nullable String key) {
        if (key == null) return 0;
        switch (key) {
            case "fluent_add": return R.drawable.ic_fluent_add;
            case "fluent_add_circle": return R.drawable.ic_fluent_add_circle;
            case "fluent_add_square": return R.drawable.ic_fluent_add_square;
            case "fluent_subtract": return R.drawable.ic_fluent_subtract;
            case "fluent_subtract_circle": return R.drawable.ic_fluent_subtract_circle;
            case "fluent_dismiss": return R.drawable.ic_fluent_dismiss;
            case "fluent_dismiss_circle": return R.drawable.ic_fluent_dismiss_circle;
            case "fluent_checkmark": return R.drawable.ic_fluent_checkmark;
            case "fluent_checkmark_circle": return R.drawable.ic_fluent_checkmark_circle;
            case "fluent_edit": return R.drawable.ic_fluent_edit;
            case "fluent_delete": return R.drawable.ic_fluent_delete;
            case "fluent_save": return R.drawable.ic_fluent_save;
            case "fluent_copy": return R.drawable.ic_fluent_copy;
            case "fluent_share": return R.drawable.ic_fluent_share;
            case "fluent_search": return R.drawable.ic_fluent_search;
            case "fluent_filter": return R.drawable.ic_fluent_filter;
            case "fluent_settings": return R.drawable.ic_fluent_settings;
            case "fluent_more_horizontal": return R.drawable.ic_fluent_more_horizontal;
            case "fluent_more_vertical": return R.drawable.ic_fluent_more_vertical;
            case "fluent_arrow_left": return R.drawable.ic_fluent_arrow_left;
            case "fluent_arrow_right": return R.drawable.ic_fluent_arrow_right;
            case "fluent_arrow_up": return R.drawable.ic_fluent_arrow_up;
            case "fluent_arrow_down": return R.drawable.ic_fluent_arrow_down;
            case "fluent_arrow_sync": return R.drawable.ic_fluent_arrow_sync;
            case "fluent_arrow_download": return R.drawable.ic_fluent_arrow_download;
            case "fluent_arrow_upload": return R.drawable.ic_fluent_arrow_upload;
            case "fluent_arrow_import": return R.drawable.ic_fluent_arrow_import;
            case "fluent_arrow_export": return R.drawable.ic_fluent_arrow_export;
            case "fluent_arrow_clockwise": return R.drawable.ic_fluent_arrow_clockwise;
            case "fluent_arrow_counterclockwise": return R.drawable.ic_fluent_arrow_counterclockwise;
            case "fluent_arrow_expand": return R.drawable.ic_fluent_arrow_expand;
            case "fluent_arrow_collapse_all": return R.drawable.ic_fluent_arrow_collapse_all;
            case "fluent_arrow_maximize": return R.drawable.ic_fluent_arrow_maximize;
            case "fluent_arrow_minimize": return R.drawable.ic_fluent_arrow_minimize;
            case "fluent_arrow_move": return R.drawable.ic_fluent_arrow_move;
            case "fluent_text_sort_ascending": return R.drawable.ic_fluent_text_sort_ascending;
            case "fluent_grid": return R.drawable.ic_fluent_grid;
            case "fluent_grid_dots": return R.drawable.ic_fluent_grid_dots;
            case "fluent_apps": return R.drawable.ic_fluent_apps;
            case "fluent_apps_list": return R.drawable.ic_fluent_apps_list;
            case "fluent_list": return R.drawable.ic_fluent_list;
            case "fluent_panel_left": return R.drawable.ic_fluent_panel_left;
            case "fluent_panel_right": return R.drawable.ic_fluent_panel_right;
            case "fluent_window": return R.drawable.ic_fluent_window;
            case "fluent_window_multiple": return R.drawable.ic_fluent_window_multiple;
            case "fluent_eye": return R.drawable.ic_fluent_eye;
            case "fluent_eye_off": return R.drawable.ic_fluent_eye_off;
            case "fluent_color": return R.drawable.ic_fluent_color;
            case "fluent_color_fill": return R.drawable.ic_fluent_color_fill;
            case "fluent_paint_brush": return R.drawable.ic_fluent_paint_brush;
            case "fluent_paint_bucket": return R.drawable.ic_fluent_paint_bucket;
            case "fluent_sparkle": return R.drawable.ic_fluent_sparkle;
            case "fluent_star": return R.drawable.ic_fluent_star;
            case "fluent_star_off": return R.drawable.ic_fluent_star_off;
            case "fluent_heart": return R.drawable.ic_fluent_heart;
            case "fluent_play": return R.drawable.ic_fluent_play;
            case "fluent_play_circle": return R.drawable.ic_fluent_play_circle;
            case "fluent_pause": return R.drawable.ic_fluent_pause;
            case "fluent_pause_circle": return R.drawable.ic_fluent_pause_circle;
            case "fluent_stop": return R.drawable.ic_fluent_stop;
            case "fluent_record": return R.drawable.ic_fluent_record;
            case "fluent_record_stop": return R.drawable.ic_fluent_record_stop;
            case "fluent_previous": return R.drawable.ic_fluent_previous;
            case "fluent_next": return R.drawable.ic_fluent_next;
            case "fluent_skip_back_10": return R.drawable.ic_fluent_skip_back_10;
            case "fluent_skip_forward_10": return R.drawable.ic_fluent_skip_forward_10;
            case "fluent_skip_forward_30": return R.drawable.ic_fluent_skip_forward_30;
            case "fluent_music_note_2": return R.drawable.ic_fluent_music_note_2;
            case "fluent_album": return R.drawable.ic_fluent_album;
            case "fluent_album_add": return R.drawable.ic_fluent_album_add;
            case "fluent_headphones": return R.drawable.ic_fluent_headphones;
            case "fluent_headphones_sound_wave": return R.drawable.ic_fluent_headphones_sound_wave;
            case "fluent_speaker_0": return R.drawable.ic_fluent_speaker_0;
            case "fluent_speaker_1": return R.drawable.ic_fluent_speaker_1;
            case "fluent_speaker_2": return R.drawable.ic_fluent_speaker_2;
            case "fluent_speaker_mute": return R.drawable.ic_fluent_speaker_mute;
            case "fluent_speaker_off": return R.drawable.ic_fluent_speaker_off;
            case "fluent_speaker_bluetooth": return R.drawable.ic_fluent_speaker_bluetooth;
            case "fluent_mic": return R.drawable.ic_fluent_mic;
            case "fluent_mic_off": return R.drawable.ic_fluent_mic_off;
            case "fluent_mic_record": return R.drawable.ic_fluent_mic_record;
            case "fluent_video": return R.drawable.ic_fluent_video;
            case "fluent_video_360": return R.drawable.ic_fluent_video_360;
            case "fluent_video_clip": return R.drawable.ic_fluent_video_clip;
            case "fluent_video_multiple": return R.drawable.ic_fluent_video_multiple;
            case "fluent_video_off": return R.drawable.ic_fluent_video_off;
            case "fluent_video_settings": return R.drawable.ic_fluent_video_settings;
            case "fluent_camera": return R.drawable.ic_fluent_camera;
            case "fluent_camera_add": return R.drawable.ic_fluent_camera_add;
            case "fluent_camera_off": return R.drawable.ic_fluent_camera_off;
            case "fluent_camera_switch": return R.drawable.ic_fluent_camera_switch;
            case "fluent_image": return R.drawable.ic_fluent_image;
            case "fluent_image_multiple": return R.drawable.ic_fluent_image_multiple;
            case "fluent_image_edit": return R.drawable.ic_fluent_image_edit;
            case "fluent_live": return R.drawable.ic_fluent_live;
            case "fluent_sound_wave_circle": return R.drawable.ic_fluent_sound_wave_circle;
            case "fluent_heart_off": return R.drawable.ic_fluent_heart_off;
            case "fluent_bookmark": return R.drawable.ic_fluent_bookmark;
            case "fluent_call": return R.drawable.ic_fluent_call;
            case "fluent_call_end": return R.drawable.ic_fluent_call_end;
            case "fluent_call_missed": return R.drawable.ic_fluent_call_missed;
            case "fluent_call_inbound": return R.drawable.ic_fluent_call_inbound;
            case "fluent_call_outbound": return R.drawable.ic_fluent_call_outbound;
            case "fluent_call_forward": return R.drawable.ic_fluent_call_forward;
            case "fluent_call_transfer": return R.drawable.ic_fluent_call_transfer;
            case "fluent_call_add": return R.drawable.ic_fluent_call_add;
            case "fluent_call_checkmark": return R.drawable.ic_fluent_call_checkmark;
            case "fluent_chat": return R.drawable.ic_fluent_chat;
            case "fluent_chat_multiple": return R.drawable.ic_fluent_chat_multiple;
            case "fluent_chat_add": return R.drawable.ic_fluent_chat_add;
            case "fluent_chat_video": return R.drawable.ic_fluent_chat_video;
            case "fluent_chat_history": return R.drawable.ic_fluent_chat_history;
            case "fluent_chat_warning": return R.drawable.ic_fluent_chat_warning;
            case "fluent_mail": return R.drawable.ic_fluent_mail;
            case "fluent_mail_inbox": return R.drawable.ic_fluent_mail_inbox;
            case "fluent_mail_add": return R.drawable.ic_fluent_mail_add;
            case "fluent_mail_alert": return R.drawable.ic_fluent_mail_alert;
            case "fluent_mail_clock": return R.drawable.ic_fluent_mail_clock;
            case "fluent_mail_checkmark": return R.drawable.ic_fluent_mail_checkmark;
            case "fluent_send": return R.drawable.ic_fluent_send;
            case "fluent_people": return R.drawable.ic_fluent_people;
            case "fluent_person": return R.drawable.ic_fluent_person;
            case "fluent_person_add": return R.drawable.ic_fluent_person_add;
            case "fluent_contact_card": return R.drawable.ic_fluent_contact_card;
            case "fluent_voicemail": return R.drawable.ic_fluent_voicemail;
            case "fluent_comment": return R.drawable.ic_fluent_comment;
            case "fluent_comment_multiple": return R.drawable.ic_fluent_comment_multiple;
            case "fluent_comment_add": return R.drawable.ic_fluent_comment_add;
            case "fluent_comment_mention": return R.drawable.ic_fluent_comment_mention;
            case "fluent_phone": return R.drawable.ic_fluent_phone;
            case "fluent_news": return R.drawable.ic_fluent_news;
            case "fluent_globe": return R.drawable.ic_fluent_globe;
            case "fluent_attach": return R.drawable.ic_fluent_attach;
            case "fluent_link": return R.drawable.ic_fluent_link;
            case "fluent_scan_qr_code": return R.drawable.ic_fluent_scan_qr_code;
            case "fluent_calendar": return R.drawable.ic_fluent_calendar;
            case "fluent_calendar_today": return R.drawable.ic_fluent_calendar_today;
            case "fluent_calendar_chat": return R.drawable.ic_fluent_calendar_chat;
            case "fluent_calendar_person": return R.drawable.ic_fluent_calendar_person;
            case "fluent_map": return R.drawable.ic_fluent_map;
            case "fluent_map_drive": return R.drawable.ic_fluent_map_drive;
            case "fluent_location": return R.drawable.ic_fluent_location;
            case "fluent_location_add": return R.drawable.ic_fluent_location_add;
            case "fluent_location_live": return R.drawable.ic_fluent_location_live;
            case "fluent_location_off": return R.drawable.ic_fluent_location_off;
            case "fluent_location_ripple": return R.drawable.ic_fluent_location_ripple;
            case "fluent_location_settings": return R.drawable.ic_fluent_location_settings;
            case "fluent_location_target_square": return R.drawable.ic_fluent_location_target_square;
            case "fluent_compass_northwest": return R.drawable.ic_fluent_compass_northwest;
            case "fluent_compass_true_north": return R.drawable.ic_fluent_compass_true_north;
            case "fluent_directions": return R.drawable.ic_fluent_directions;
            case "fluent_navigation": return R.drawable.ic_fluent_navigation;
            case "fluent_navigation_person": return R.drawable.ic_fluent_navigation_person;
            case "fluent_road": return R.drawable.ic_fluent_road;
            case "fluent_road_cone": return R.drawable.ic_fluent_road_cone;
            case "fluent_earth": return R.drawable.ic_fluent_earth;
            case "fluent_earth_leaf": return R.drawable.ic_fluent_earth_leaf;
            case "fluent_globe_location": return R.drawable.ic_fluent_globe_location;
            case "fluent_globe_search": return R.drawable.ic_fluent_globe_search;
            case "fluent_branch_fork": return R.drawable.ic_fluent_branch_fork;
            case "fluent_branch_fork_hint": return R.drawable.ic_fluent_branch_fork_hint;
            case "fluent_target": return R.drawable.ic_fluent_target;
            case "fluent_target_add": return R.drawable.ic_fluent_target_add;
            case "fluent_target_arrow": return R.drawable.ic_fluent_target_arrow;
            case "fluent_scan_object": return R.drawable.ic_fluent_scan_object;
            case "fluent_scan_camera": return R.drawable.ic_fluent_scan_camera;
            case "fluent_weather_duststorm": return R.drawable.ic_fluent_weather_duststorm;
            case "fluent_arrow_routing": return R.drawable.ic_fluent_arrow_routing;
            case "fluent_arrow_routing_rectangle_multiple": return R.drawable.ic_fluent_arrow_routing_rectangle_multiple;
            case "fluent_vehicle_car": return R.drawable.ic_fluent_vehicle_car;
            case "fluent_vehicle_car_collision": return R.drawable.ic_fluent_vehicle_car_collision;
            case "fluent_vehicle_car_parking": return R.drawable.ic_fluent_vehicle_car_parking;
            case "fluent_vehicle_car_profile": return R.drawable.ic_fluent_vehicle_car_profile;
            case "fluent_vehicle_cable_car": return R.drawable.ic_fluent_vehicle_cable_car;
            case "fluent_vehicle_car_profile_ltr_clock": return R.drawable.ic_fluent_vehicle_car_profile_ltr_clock;
            case "fluent_vehicle_truck": return R.drawable.ic_fluent_vehicle_truck;
            case "fluent_vehicle_truck_profile": return R.drawable.ic_fluent_vehicle_truck_profile;
            case "fluent_vehicle_truck_checkmark": return R.drawable.ic_fluent_vehicle_truck_checkmark;
            case "fluent_vehicle_truck_bag": return R.drawable.ic_fluent_vehicle_truck_bag;
            case "fluent_vehicle_bus": return R.drawable.ic_fluent_vehicle_bus;
            case "fluent_vehicle_cab": return R.drawable.ic_fluent_vehicle_cab;
            case "fluent_vehicle_motorcycle": return R.drawable.ic_fluent_vehicle_motorcycle;
            case "fluent_vehicle_bicycle": return R.drawable.ic_fluent_vehicle_bicycle;
            case "fluent_vehicle_tractor": return R.drawable.ic_fluent_vehicle_tractor;
            case "fluent_gas": return R.drawable.ic_fluent_gas;
            case "fluent_gas_pump": return R.drawable.ic_fluent_gas_pump;
            case "fluent_engine": return R.drawable.ic_fluent_engine;
            case "fluent_seat": return R.drawable.ic_fluent_seat;
            case "fluent_flash": return R.drawable.ic_fluent_flash;
            case "fluent_flash_auto": return R.drawable.ic_fluent_flash_auto;
            case "fluent_key": return R.drawable.ic_fluent_key;
            case "fluent_toolbox": return R.drawable.ic_fluent_toolbox;
            case "fluent_wrench": return R.drawable.ic_fluent_wrench;
            case "fluent_wrench_screwdriver": return R.drawable.ic_fluent_wrench_screwdriver;
            case "fluent_shield_checkmark": return R.drawable.ic_fluent_shield_checkmark;
            case "fluent_battery_charge": return R.drawable.ic_fluent_battery_charge;
            case "fluent_temperature": return R.drawable.ic_fluent_temperature;
            case "fluent_weather_snowflake": return R.drawable.ic_fluent_weather_snowflake;
            case "fluent_home": return R.drawable.ic_fluent_home;
            case "fluent_home_add": return R.drawable.ic_fluent_home_add;
            case "fluent_home_garage": return R.drawable.ic_fluent_home_garage;
            case "fluent_home_heart": return R.drawable.ic_fluent_home_heart;
            case "fluent_home_person": return R.drawable.ic_fluent_home_person;
            case "fluent_home_more": return R.drawable.ic_fluent_home_more;
            case "fluent_building_home": return R.drawable.ic_fluent_building_home;
            case "fluent_door": return R.drawable.ic_fluent_door;
            case "fluent_door_arrow_left": return R.drawable.ic_fluent_door_arrow_left;
            case "fluent_door_tag": return R.drawable.ic_fluent_door_tag;
            case "fluent_lock_closed": return R.drawable.ic_fluent_lock_closed;
            case "fluent_lock_open": return R.drawable.ic_fluent_lock_open;
            case "fluent_lightbulb": return R.drawable.ic_fluent_lightbulb;
            case "fluent_lightbulb_circle": return R.drawable.ic_fluent_lightbulb_circle;
            case "fluent_lightbulb_pulse": return R.drawable.ic_fluent_lightbulb_pulse;
            case "fluent_plug_connected": return R.drawable.ic_fluent_plug_connected;
            case "fluent_plug_connected_settings": return R.drawable.ic_fluent_plug_connected_settings;
            case "fluent_plug_disconnected": return R.drawable.ic_fluent_plug_disconnected;
            case "fluent_power": return R.drawable.ic_fluent_power;
            case "fluent_water": return R.drawable.ic_fluent_water;
            case "fluent_drop": return R.drawable.ic_fluent_drop;
            case "fluent_fire": return R.drawable.ic_fluent_fire;
            case "fluent_fireplace": return R.drawable.ic_fluent_fireplace;
            case "fluent_camera_dome": return R.drawable.ic_fluent_camera_dome;
            case "fluent_wifi_1": return R.drawable.ic_fluent_wifi_1;
            case "fluent_wifi_2": return R.drawable.ic_fluent_wifi_2;
            case "fluent_wifi_3": return R.drawable.ic_fluent_wifi_3;
            case "fluent_wifi_4": return R.drawable.ic_fluent_wifi_4;
            case "fluent_router": return R.drawable.ic_fluent_router;
            case "fluent_router_off": return R.drawable.ic_fluent_router_off;
            case "fluent_bluetooth": return R.drawable.ic_fluent_bluetooth;
            case "fluent_bluetooth_connected": return R.drawable.ic_fluent_bluetooth_connected;
            case "fluent_bluetooth_disabled": return R.drawable.ic_fluent_bluetooth_disabled;
            case "fluent_battery_0": return R.drawable.ic_fluent_battery_0;
            case "fluent_battery_5": return R.drawable.ic_fluent_battery_5;
            case "fluent_battery_10": return R.drawable.ic_fluent_battery_10;
            case "fluent_clock_alarm": return R.drawable.ic_fluent_clock_alarm;
            case "fluent_clock_warning": return R.drawable.ic_fluent_clock_warning;
            case "fluent_presence_available": return R.drawable.ic_fluent_presence_available;
            case "fluent_presence_away": return R.drawable.ic_fluent_presence_away;
            case "fluent_presence_busy": return R.drawable.ic_fluent_presence_busy;
            case "fluent_leaf_two": return R.drawable.ic_fluent_leaf_two;
            case "fluent_animal_dog": return R.drawable.ic_fluent_animal_dog;
            case "fluent_weather_sunny": return R.drawable.ic_fluent_weather_sunny;
            case "fluent_weather_cloudy": return R.drawable.ic_fluent_weather_cloudy;
            case "fluent_weather_rain": return R.drawable.ic_fluent_weather_rain;
            case "fluent_weather_thunderstorm": return R.drawable.ic_fluent_weather_thunderstorm;
            case "fluent_shield": return R.drawable.ic_fluent_shield;
            case "fluent_shield_dismiss": return R.drawable.ic_fluent_shield_dismiss;
            case "fluent_shield_error": return R.drawable.ic_fluent_shield_error;
            case "fluent_shield_lock": return R.drawable.ic_fluent_shield_lock;
            case "fluent_shield_keyhole": return R.drawable.ic_fluent_shield_keyhole;
            case "fluent_shield_prohibited": return R.drawable.ic_fluent_shield_prohibited;
            case "fluent_shield_question": return R.drawable.ic_fluent_shield_question;
            case "fluent_shield_settings": return R.drawable.ic_fluent_shield_settings;
            case "fluent_shield_task": return R.drawable.ic_fluent_shield_task;
            case "fluent_lock_shield": return R.drawable.ic_fluent_lock_shield;
            case "fluent_key_multiple": return R.drawable.ic_fluent_key_multiple;
            case "fluent_alert": return R.drawable.ic_fluent_alert;
            case "fluent_alert_badge": return R.drawable.ic_fluent_alert_badge;
            case "fluent_alert_off": return R.drawable.ic_fluent_alert_off;
            case "fluent_alert_on": return R.drawable.ic_fluent_alert_on;
            case "fluent_alert_urgent": return R.drawable.ic_fluent_alert_urgent;
            case "fluent_info": return R.drawable.ic_fluent_info;
            case "fluent_error_circle": return R.drawable.ic_fluent_error_circle;
            case "fluent_question_circle": return R.drawable.ic_fluent_question_circle;
            case "fluent_fingerprint": return R.drawable.ic_fluent_fingerprint;
            case "fluent_password": return R.drawable.ic_fluent_password;
            case "fluent_incognito": return R.drawable.ic_fluent_incognito;
            case "fluent_certificate": return R.drawable.ic_fluent_certificate;
            case "fluent_scan_person": return R.drawable.ic_fluent_scan_person;
            case "fluent_flashlight": return R.drawable.ic_fluent_flashlight;
            case "fluent_flashlight_off": return R.drawable.ic_fluent_flashlight_off;
            case "fluent_cloud_checkmark": return R.drawable.ic_fluent_cloud_checkmark;
            case "fluent_cloud_error": return R.drawable.ic_fluent_cloud_error;
            case "fluent_person_warning": return R.drawable.ic_fluent_person_warning;
            case "fluent_briefcase": return R.drawable.ic_fluent_briefcase;
            case "fluent_briefcase_medical": return R.drawable.ic_fluent_briefcase_medical;
            case "fluent_calculator": return R.drawable.ic_fluent_calculator;
            case "fluent_document": return R.drawable.ic_fluent_document;
            case "fluent_document_add": return R.drawable.ic_fluent_document_add;
            case "fluent_document_edit": return R.drawable.ic_fluent_document_edit;
            case "fluent_document_save": return R.drawable.ic_fluent_document_save;
            case "fluent_document_search": return R.drawable.ic_fluent_document_search;
            case "fluent_document_pdf": return R.drawable.ic_fluent_document_pdf;
            case "fluent_document_signature": return R.drawable.ic_fluent_document_signature;
            case "fluent_folder": return R.drawable.ic_fluent_folder;
            case "fluent_folder_open": return R.drawable.ic_fluent_folder_open;
            case "fluent_folder_add": return R.drawable.ic_fluent_folder_add;
            case "fluent_clipboard": return R.drawable.ic_fluent_clipboard;
            case "fluent_clipboard_checkmark": return R.drawable.ic_fluent_clipboard_checkmark;
            case "fluent_clipboard_task": return R.drawable.ic_fluent_clipboard_task;
            case "fluent_code": return R.drawable.ic_fluent_code;
            case "fluent_code_block": return R.drawable.ic_fluent_code_block;
            case "fluent_database": return R.drawable.ic_fluent_database;
            case "fluent_database_search": return R.drawable.ic_fluent_database_search;
            case "fluent_print": return R.drawable.ic_fluent_print;
            case "fluent_scan": return R.drawable.ic_fluent_scan;
            case "fluent_ruler": return R.drawable.ic_fluent_ruler;
            case "fluent_compose": return R.drawable.ic_fluent_compose;
            case "fluent_organization": return R.drawable.ic_fluent_organization;
            case "fluent_building": return R.drawable.ic_fluent_building;
            case "fluent_building_bank": return R.drawable.ic_fluent_building_bank;
            case "fluent_building_factory": return R.drawable.ic_fluent_building_factory;
            case "fluent_building_shop": return R.drawable.ic_fluent_building_shop;
            case "fluent_cart": return R.drawable.ic_fluent_cart;
            case "fluent_shopping_bag": return R.drawable.ic_fluent_shopping_bag;
            case "fluent_wallet": return R.drawable.ic_fluent_wallet;
            case "fluent_wallet_credit_card": return R.drawable.ic_fluent_wallet_credit_card;
            case "fluent_payment": return R.drawable.ic_fluent_payment;
            case "fluent_receipt": return R.drawable.ic_fluent_receipt;
            case "fluent_receipt_money": return R.drawable.ic_fluent_receipt_money;
            case "fluent_money": return R.drawable.ic_fluent_money;
            case "fluent_money_hand": return R.drawable.ic_fluent_money_hand;
            case "fluent_gift": return R.drawable.ic_fluent_gift;
            case "fluent_trophy": return R.drawable.ic_fluent_trophy;
            case "fluent_book": return R.drawable.ic_fluent_book;
            case "fluent_book_open": return R.drawable.ic_fluent_book_open;
            case "fluent_learning_app": return R.drawable.ic_fluent_learning_app;
            case "fluent_pill": return R.drawable.ic_fluent_pill;
            case "fluent_food": return R.drawable.ic_fluent_food;
            case "fluent_food_apple": return R.drawable.ic_fluent_food_apple;
            case "fluent_food_cake": return R.drawable.ic_fluent_food_cake;
            case "fluent_food_pizza": return R.drawable.ic_fluent_food_pizza;
            default: return 0;
        }
    }

    @NonNull private static List<LauncherIconResolver.Preset> buildPresets() {
        List<LauncherIconResolver.Preset> result = new ArrayList<>(ICON_COUNT);
            result.add(new LauncherIconResolver.Preset("fluent_add", "Добавить", "Интерфейс", "add"));
            result.add(new LauncherIconResolver.Preset("fluent_add_circle", "Добавить круг", "Интерфейс", "add circle"));
            result.add(new LauncherIconResolver.Preset("fluent_add_square", "Добавить квадрат", "Интерфейс", "add square"));
            result.add(new LauncherIconResolver.Preset("fluent_subtract", "Убрать", "Интерфейс", "subtract"));
            result.add(new LauncherIconResolver.Preset("fluent_subtract_circle", "Убрать круг", "Интерфейс", "subtract circle"));
            result.add(new LauncherIconResolver.Preset("fluent_dismiss", "Закрыть", "Интерфейс", "dismiss"));
            result.add(new LauncherIconResolver.Preset("fluent_dismiss_circle", "Закрыть круг", "Интерфейс", "dismiss circle"));
            result.add(new LauncherIconResolver.Preset("fluent_checkmark", "Готово", "Интерфейс", "checkmark"));
            result.add(new LauncherIconResolver.Preset("fluent_checkmark_circle", "Готово круг", "Интерфейс", "checkmark circle"));
            result.add(new LauncherIconResolver.Preset("fluent_edit", "Изменить", "Интерфейс", "edit"));
            result.add(new LauncherIconResolver.Preset("fluent_delete", "Удалить", "Интерфейс", "delete"));
            result.add(new LauncherIconResolver.Preset("fluent_save", "Сохранить", "Интерфейс", "save"));
            result.add(new LauncherIconResolver.Preset("fluent_copy", "Копировать", "Интерфейс", "copy"));
            result.add(new LauncherIconResolver.Preset("fluent_share", "Поделиться", "Интерфейс", "share"));
            result.add(new LauncherIconResolver.Preset("fluent_search", "Поиск", "Интерфейс", "search"));
            result.add(new LauncherIconResolver.Preset("fluent_filter", "Фильтр", "Интерфейс", "filter"));
            result.add(new LauncherIconResolver.Preset("fluent_settings", "Настройки", "Интерфейс", "settings"));
            result.add(new LauncherIconResolver.Preset("fluent_more_horizontal", "Ещё горизонтально", "Интерфейс", "more horizontal"));
            result.add(new LauncherIconResolver.Preset("fluent_more_vertical", "Ещё вертикально", "Интерфейс", "more vertical"));
            result.add(new LauncherIconResolver.Preset("fluent_arrow_left", "Стрелка влево", "Интерфейс", "arrow left"));
            result.add(new LauncherIconResolver.Preset("fluent_arrow_right", "Стрелка вправо", "Интерфейс", "arrow right"));
            result.add(new LauncherIconResolver.Preset("fluent_arrow_up", "Стрелка вверх", "Интерфейс", "arrow up"));
            result.add(new LauncherIconResolver.Preset("fluent_arrow_down", "Стрелка вниз", "Интерфейс", "arrow down"));
            result.add(new LauncherIconResolver.Preset("fluent_arrow_sync", "Стрелка синхронизация", "Интерфейс", "arrow sync"));
            result.add(new LauncherIconResolver.Preset("fluent_arrow_download", "Стрелка скачать", "Интерфейс", "arrow download"));
            result.add(new LauncherIconResolver.Preset("fluent_arrow_upload", "Стрелка загрузить", "Интерфейс", "arrow upload"));
            result.add(new LauncherIconResolver.Preset("fluent_arrow_import", "Стрелка импорт", "Интерфейс", "arrow import"));
            result.add(new LauncherIconResolver.Preset("fluent_arrow_export", "Стрелка экспорт", "Интерфейс", "arrow export"));
            result.add(new LauncherIconResolver.Preset("fluent_arrow_clockwise", "Стрелка по часовой", "Интерфейс", "arrow clockwise"));
            result.add(new LauncherIconResolver.Preset("fluent_arrow_counterclockwise", "Стрелка против часовой", "Интерфейс", "arrow counterclockwise"));
            result.add(new LauncherIconResolver.Preset("fluent_arrow_expand", "Стрелка развернуть", "Интерфейс", "arrow expand"));
            result.add(new LauncherIconResolver.Preset("fluent_arrow_collapse_all", "Стрелка свернуть всё", "Интерфейс", "arrow collapse all"));
            result.add(new LauncherIconResolver.Preset("fluent_arrow_maximize", "Стрелка увеличить", "Интерфейс", "arrow maximize"));
            result.add(new LauncherIconResolver.Preset("fluent_arrow_minimize", "Стрелка уменьшить", "Интерфейс", "arrow minimize"));
            result.add(new LauncherIconResolver.Preset("fluent_arrow_move", "Стрелка переместить", "Интерфейс", "arrow move"));
            result.add(new LauncherIconResolver.Preset("fluent_text_sort_ascending", "Текст сортировка по возрастанию", "Интерфейс", "text sort ascending"));
            result.add(new LauncherIconResolver.Preset("fluent_grid", "Сетка", "Интерфейс", "grid"));
            result.add(new LauncherIconResolver.Preset("fluent_grid_dots", "Сетка точки", "Интерфейс", "grid dots"));
            result.add(new LauncherIconResolver.Preset("fluent_apps", "Приложения", "Интерфейс", "apps"));
            result.add(new LauncherIconResolver.Preset("fluent_apps_list", "Приложения список", "Интерфейс", "apps list"));
            result.add(new LauncherIconResolver.Preset("fluent_list", "Список", "Интерфейс", "list"));
            result.add(new LauncherIconResolver.Preset("fluent_panel_left", "Панель влево", "Интерфейс", "panel left"));
            result.add(new LauncherIconResolver.Preset("fluent_panel_right", "Панель вправо", "Интерфейс", "panel right"));
            result.add(new LauncherIconResolver.Preset("fluent_window", "Окно", "Интерфейс", "window"));
            result.add(new LauncherIconResolver.Preset("fluent_window_multiple", "Окно несколько", "Интерфейс", "window multiple"));
            result.add(new LauncherIconResolver.Preset("fluent_eye", "Видимость", "Интерфейс", "eye"));
            result.add(new LauncherIconResolver.Preset("fluent_eye_off", "Видимость выключено", "Интерфейс", "eye off"));
            result.add(new LauncherIconResolver.Preset("fluent_color", "Цвет", "Интерфейс", "color"));
            result.add(new LauncherIconResolver.Preset("fluent_color_fill", "Цвет заливка", "Интерфейс", "color fill"));
            result.add(new LauncherIconResolver.Preset("fluent_paint_brush", "Краска кисть", "Интерфейс", "paint brush"));
            result.add(new LauncherIconResolver.Preset("fluent_paint_bucket", "Краска ведро", "Интерфейс", "paint bucket"));
            result.add(new LauncherIconResolver.Preset("fluent_sparkle", "Эффект", "Интерфейс", "sparkle"));
            result.add(new LauncherIconResolver.Preset("fluent_star", "Звезда", "Интерфейс", "star"));
            result.add(new LauncherIconResolver.Preset("fluent_star_off", "Звезда выключено", "Интерфейс", "star off"));
            result.add(new LauncherIconResolver.Preset("fluent_heart", "Сердце", "Интерфейс", "heart"));
            result.add(new LauncherIconResolver.Preset("fluent_play", "Воспроизвести", "Медиа", "play"));
            result.add(new LauncherIconResolver.Preset("fluent_play_circle", "Воспроизвести круг", "Медиа", "play circle"));
            result.add(new LauncherIconResolver.Preset("fluent_pause", "Пауза", "Медиа", "pause"));
            result.add(new LauncherIconResolver.Preset("fluent_pause_circle", "Пауза круг", "Медиа", "pause circle"));
            result.add(new LauncherIconResolver.Preset("fluent_stop", "Стоп", "Медиа", "stop"));
            result.add(new LauncherIconResolver.Preset("fluent_record", "Запись", "Медиа", "record"));
            result.add(new LauncherIconResolver.Preset("fluent_record_stop", "Запись стоп", "Медиа", "record stop"));
            result.add(new LauncherIconResolver.Preset("fluent_previous", "Предыдущий", "Медиа", "previous"));
            result.add(new LauncherIconResolver.Preset("fluent_next", "Следующий", "Медиа", "next"));
            result.add(new LauncherIconResolver.Preset("fluent_skip_back_10", "Перемотка назад", "Медиа", "skip back 10"));
            result.add(new LauncherIconResolver.Preset("fluent_skip_forward_10", "Перемотка вперёд", "Медиа", "skip forward 10"));
            result.add(new LauncherIconResolver.Preset("fluent_skip_forward_30", "Перемотка вперёд", "Медиа", "skip forward 30"));
            result.add(new LauncherIconResolver.Preset("fluent_music_note_2", "Музыка нота", "Медиа", "music note 2"));
            result.add(new LauncherIconResolver.Preset("fluent_album", "Альбом", "Медиа", "album"));
            result.add(new LauncherIconResolver.Preset("fluent_album_add", "Альбом добавить", "Медиа", "album add"));
            result.add(new LauncherIconResolver.Preset("fluent_headphones", "Наушники", "Медиа", "headphones"));
            result.add(new LauncherIconResolver.Preset("fluent_headphones_sound_wave", "Наушники звук волна", "Медиа", "headphones sound wave"));
            result.add(new LauncherIconResolver.Preset("fluent_speaker_0", "Динамик", "Медиа", "speaker 0"));
            result.add(new LauncherIconResolver.Preset("fluent_speaker_1", "Динамик", "Медиа", "speaker 1"));
            result.add(new LauncherIconResolver.Preset("fluent_speaker_2", "Динамик", "Медиа", "speaker 2"));
            result.add(new LauncherIconResolver.Preset("fluent_speaker_mute", "Динамик без звука", "Медиа", "speaker mute"));
            result.add(new LauncherIconResolver.Preset("fluent_speaker_off", "Динамик выключено", "Медиа", "speaker off"));
            result.add(new LauncherIconResolver.Preset("fluent_speaker_bluetooth", "Динамик Bluetooth", "Медиа", "speaker bluetooth"));
            result.add(new LauncherIconResolver.Preset("fluent_mic", "Микрофон", "Медиа", "mic"));
            result.add(new LauncherIconResolver.Preset("fluent_mic_off", "Микрофон выключено", "Медиа", "mic off"));
            result.add(new LauncherIconResolver.Preset("fluent_mic_record", "Микрофон запись", "Медиа", "mic record"));
            result.add(new LauncherIconResolver.Preset("fluent_video", "Видео", "Медиа", "video"));
            result.add(new LauncherIconResolver.Preset("fluent_video_360", "Видео", "Медиа", "video 360"));
            result.add(new LauncherIconResolver.Preset("fluent_video_clip", "Видео клип", "Медиа", "video clip"));
            result.add(new LauncherIconResolver.Preset("fluent_video_multiple", "Видео несколько", "Медиа", "video multiple"));
            result.add(new LauncherIconResolver.Preset("fluent_video_off", "Видео выключено", "Медиа", "video off"));
            result.add(new LauncherIconResolver.Preset("fluent_video_settings", "Видео настройки", "Медиа", "video settings"));
            result.add(new LauncherIconResolver.Preset("fluent_camera", "Камера", "Медиа", "camera"));
            result.add(new LauncherIconResolver.Preset("fluent_camera_add", "Камера добавить", "Медиа", "camera add"));
            result.add(new LauncherIconResolver.Preset("fluent_camera_off", "Камера выключено", "Медиа", "camera off"));
            result.add(new LauncherIconResolver.Preset("fluent_camera_switch", "Камера переключить", "Медиа", "camera switch"));
            result.add(new LauncherIconResolver.Preset("fluent_image", "Изображение", "Медиа", "image"));
            result.add(new LauncherIconResolver.Preset("fluent_image_multiple", "Изображение несколько", "Медиа", "image multiple"));
            result.add(new LauncherIconResolver.Preset("fluent_image_edit", "Изображение изменить", "Медиа", "image edit"));
            result.add(new LauncherIconResolver.Preset("fluent_live", "Эфир", "Медиа", "live"));
            result.add(new LauncherIconResolver.Preset("fluent_sound_wave_circle", "Звук волна круг", "Медиа", "sound wave circle"));
            result.add(new LauncherIconResolver.Preset("fluent_heart_off", "Сердце выключено", "Медиа", "heart off"));
            result.add(new LauncherIconResolver.Preset("fluent_bookmark", "Закладка", "Медиа", "bookmark"));
            result.add(new LauncherIconResolver.Preset("fluent_call", "Звонок", "Связь", "call"));
            result.add(new LauncherIconResolver.Preset("fluent_call_end", "Звонок завершить", "Связь", "call end"));
            result.add(new LauncherIconResolver.Preset("fluent_call_missed", "Звонок пропущенный", "Связь", "call missed"));
            result.add(new LauncherIconResolver.Preset("fluent_call_inbound", "Звонок входящий", "Связь", "call inbound"));
            result.add(new LauncherIconResolver.Preset("fluent_call_outbound", "Звонок исходящий", "Связь", "call outbound"));
            result.add(new LauncherIconResolver.Preset("fluent_call_forward", "Звонок вперёд", "Связь", "call forward"));
            result.add(new LauncherIconResolver.Preset("fluent_call_transfer", "Звонок перевести", "Связь", "call transfer"));
            result.add(new LauncherIconResolver.Preset("fluent_call_add", "Звонок добавить", "Связь", "call add"));
            result.add(new LauncherIconResolver.Preset("fluent_call_checkmark", "Звонок готово", "Связь", "call checkmark"));
            result.add(new LauncherIconResolver.Preset("fluent_chat", "Чат", "Связь", "chat"));
            result.add(new LauncherIconResolver.Preset("fluent_chat_multiple", "Чат несколько", "Связь", "chat multiple"));
            result.add(new LauncherIconResolver.Preset("fluent_chat_add", "Чат добавить", "Связь", "chat add"));
            result.add(new LauncherIconResolver.Preset("fluent_chat_video", "Чат видео", "Связь", "chat video"));
            result.add(new LauncherIconResolver.Preset("fluent_chat_history", "Чат история", "Связь", "chat history"));
            result.add(new LauncherIconResolver.Preset("fluent_chat_warning", "Чат опасность", "Связь", "chat warning"));
            result.add(new LauncherIconResolver.Preset("fluent_mail", "Почта", "Связь", "mail"));
            result.add(new LauncherIconResolver.Preset("fluent_mail_inbox", "Почта входящие", "Связь", "mail inbox"));
            result.add(new LauncherIconResolver.Preset("fluent_mail_add", "Почта добавить", "Связь", "mail add"));
            result.add(new LauncherIconResolver.Preset("fluent_mail_alert", "Почта предупреждение", "Связь", "mail alert"));
            result.add(new LauncherIconResolver.Preset("fluent_mail_clock", "Почта часы", "Связь", "mail clock"));
            result.add(new LauncherIconResolver.Preset("fluent_mail_checkmark", "Почта готово", "Связь", "mail checkmark"));
            result.add(new LauncherIconResolver.Preset("fluent_send", "Отправить", "Связь", "send"));
            result.add(new LauncherIconResolver.Preset("fluent_people", "Люди", "Связь", "people"));
            result.add(new LauncherIconResolver.Preset("fluent_person", "Человек", "Связь", "person"));
            result.add(new LauncherIconResolver.Preset("fluent_person_add", "Человек добавить", "Связь", "person add"));
            result.add(new LauncherIconResolver.Preset("fluent_contact_card", "Контакт карточка", "Связь", "contact card"));
            result.add(new LauncherIconResolver.Preset("fluent_voicemail", "Автоответчик", "Связь", "voicemail"));
            result.add(new LauncherIconResolver.Preset("fluent_comment", "Комментарий", "Связь", "comment"));
            result.add(new LauncherIconResolver.Preset("fluent_comment_multiple", "Комментарий несколько", "Связь", "comment multiple"));
            result.add(new LauncherIconResolver.Preset("fluent_comment_add", "Комментарий добавить", "Связь", "comment add"));
            result.add(new LauncherIconResolver.Preset("fluent_comment_mention", "Комментарий упоминание", "Связь", "comment mention"));
            result.add(new LauncherIconResolver.Preset("fluent_phone", "Телефон", "Связь", "phone"));
            result.add(new LauncherIconResolver.Preset("fluent_news", "Новости", "Связь", "news"));
            result.add(new LauncherIconResolver.Preset("fluent_globe", "Мир", "Связь", "globe"));
            result.add(new LauncherIconResolver.Preset("fluent_attach", "Вложение", "Связь", "attach"));
            result.add(new LauncherIconResolver.Preset("fluent_link", "Ссылка", "Связь", "link"));
            result.add(new LauncherIconResolver.Preset("fluent_scan_qr_code", "Сканировать QR код", "Связь", "scan qr code"));
            result.add(new LauncherIconResolver.Preset("fluent_calendar", "Календарь", "Связь", "calendar"));
            result.add(new LauncherIconResolver.Preset("fluent_calendar_today", "Календарь сегодня", "Связь", "calendar today"));
            result.add(new LauncherIconResolver.Preset("fluent_calendar_chat", "Календарь чат", "Связь", "calendar chat"));
            result.add(new LauncherIconResolver.Preset("fluent_calendar_person", "Календарь человек", "Связь", "calendar person"));
            result.add(new LauncherIconResolver.Preset("fluent_map", "Карта", "Навигация", "map"));
            result.add(new LauncherIconResolver.Preset("fluent_map_drive", "Карта поездка", "Навигация", "map drive"));
            result.add(new LauncherIconResolver.Preset("fluent_location", "Геопозиция", "Навигация", "location"));
            result.add(new LauncherIconResolver.Preset("fluent_location_add", "Геопозиция добавить", "Навигация", "location add"));
            result.add(new LauncherIconResolver.Preset("fluent_location_live", "Геопозиция эфир", "Навигация", "location live"));
            result.add(new LauncherIconResolver.Preset("fluent_location_off", "Геопозиция выключено", "Навигация", "location off"));
            result.add(new LauncherIconResolver.Preset("fluent_location_ripple", "Геопозиция сигнал", "Навигация", "location ripple"));
            result.add(new LauncherIconResolver.Preset("fluent_location_settings", "Геопозиция настройки", "Навигация", "location settings"));
            result.add(new LauncherIconResolver.Preset("fluent_location_target_square", "Геопозиция цель квадрат", "Навигация", "location target square"));
            result.add(new LauncherIconResolver.Preset("fluent_compass_northwest", "Компас северо-запад", "Навигация", "compass northwest"));
            result.add(new LauncherIconResolver.Preset("fluent_compass_true_north", "Компас точный север", "Навигация", "compass true north"));
            result.add(new LauncherIconResolver.Preset("fluent_directions", "Маршрут", "Навигация", "directions"));
            result.add(new LauncherIconResolver.Preset("fluent_navigation", "Навигация", "Навигация", "navigation"));
            result.add(new LauncherIconResolver.Preset("fluent_navigation_person", "Навигация человек", "Навигация", "navigation person"));
            result.add(new LauncherIconResolver.Preset("fluent_road", "Дорога", "Навигация", "road"));
            result.add(new LauncherIconResolver.Preset("fluent_road_cone", "Дорога конус", "Навигация", "road cone"));
            result.add(new LauncherIconResolver.Preset("fluent_earth", "Земля", "Навигация", "earth"));
            result.add(new LauncherIconResolver.Preset("fluent_earth_leaf", "Земля лист", "Навигация", "earth leaf"));
            result.add(new LauncherIconResolver.Preset("fluent_globe_location", "Мир геопозиция", "Навигация", "globe location"));
            result.add(new LauncherIconResolver.Preset("fluent_globe_search", "Мир поиск", "Навигация", "globe search"));
            result.add(new LauncherIconResolver.Preset("fluent_branch_fork", "Развилка ветка", "Навигация", "branch fork"));
            result.add(new LauncherIconResolver.Preset("fluent_branch_fork_hint", "Развилка ветка подсказка", "Навигация", "branch fork hint"));
            result.add(new LauncherIconResolver.Preset("fluent_target", "Цель", "Навигация", "target"));
            result.add(new LauncherIconResolver.Preset("fluent_target_add", "Цель добавить", "Навигация", "target add"));
            result.add(new LauncherIconResolver.Preset("fluent_target_arrow", "Цель стрелка", "Навигация", "target arrow"));
            result.add(new LauncherIconResolver.Preset("fluent_scan_object", "Сканировать объект", "Навигация", "scan object"));
            result.add(new LauncherIconResolver.Preset("fluent_scan_camera", "Сканировать камера", "Навигация", "scan camera"));
            result.add(new LauncherIconResolver.Preset("fluent_weather_duststorm", "Погода пыль", "Навигация", "weather duststorm"));
            result.add(new LauncherIconResolver.Preset("fluent_arrow_routing", "Стрелка маршрутизация", "Навигация", "arrow routing"));
            result.add(new LauncherIconResolver.Preset("fluent_arrow_routing_rectangle_multiple", "Стрелка маршрутизация прямоугольник несколько", "Навигация", "arrow routing rectangle multiple"));
            result.add(new LauncherIconResolver.Preset("fluent_vehicle_car", "Транспорт автомобиль", "Автомобиль", "vehicle car"));
            result.add(new LauncherIconResolver.Preset("fluent_vehicle_car_collision", "Транспорт автомобиль авария", "Автомобиль", "vehicle car collision"));
            result.add(new LauncherIconResolver.Preset("fluent_vehicle_car_parking", "Транспорт автомобиль парковка", "Автомобиль", "vehicle car parking"));
            result.add(new LauncherIconResolver.Preset("fluent_vehicle_car_profile", "Транспорт автомобиль профиль", "Автомобиль", "vehicle car profile"));
            result.add(new LauncherIconResolver.Preset("fluent_vehicle_cable_car", "Транспорт канатный автомобиль", "Автомобиль", "vehicle cable car"));
            result.add(new LauncherIconResolver.Preset("fluent_vehicle_car_profile_ltr_clock", "Транспорт автомобиль профиль слева направо часы", "Автомобиль", "vehicle car profile ltr clock"));
            result.add(new LauncherIconResolver.Preset("fluent_vehicle_truck", "Транспорт грузовик", "Автомобиль", "vehicle truck"));
            result.add(new LauncherIconResolver.Preset("fluent_vehicle_truck_profile", "Транспорт грузовик профиль", "Автомобиль", "vehicle truck profile"));
            result.add(new LauncherIconResolver.Preset("fluent_vehicle_truck_checkmark", "Транспорт грузовик готово", "Автомобиль", "vehicle truck checkmark"));
            result.add(new LauncherIconResolver.Preset("fluent_vehicle_truck_bag", "Транспорт грузовик сумка", "Автомобиль", "vehicle truck bag"));
            result.add(new LauncherIconResolver.Preset("fluent_vehicle_bus", "Транспорт автобус", "Автомобиль", "vehicle bus"));
            result.add(new LauncherIconResolver.Preset("fluent_vehicle_cab", "Транспорт такси", "Автомобиль", "vehicle cab"));
            result.add(new LauncherIconResolver.Preset("fluent_vehicle_motorcycle", "Транспорт мотоцикл", "Автомобиль", "vehicle motorcycle"));
            result.add(new LauncherIconResolver.Preset("fluent_vehicle_bicycle", "Транспорт велосипед", "Автомобиль", "vehicle bicycle"));
            result.add(new LauncherIconResolver.Preset("fluent_vehicle_tractor", "Транспорт трактор", "Автомобиль", "vehicle tractor"));
            result.add(new LauncherIconResolver.Preset("fluent_gas", "Топливо", "Автомобиль", "gas"));
            result.add(new LauncherIconResolver.Preset("fluent_gas_pump", "Топливо заправка", "Автомобиль", "gas pump"));
            result.add(new LauncherIconResolver.Preset("fluent_engine", "Двигатель", "Автомобиль", "engine"));
            result.add(new LauncherIconResolver.Preset("fluent_seat", "Сиденье", "Автомобиль", "seat"));
            result.add(new LauncherIconResolver.Preset("fluent_flash", "Вспышка", "Автомобиль", "flash"));
            result.add(new LauncherIconResolver.Preset("fluent_flash_auto", "Вспышка авто", "Автомобиль", "flash auto"));
            result.add(new LauncherIconResolver.Preset("fluent_key", "Ключ", "Автомобиль", "key"));
            result.add(new LauncherIconResolver.Preset("fluent_toolbox", "Инструменты", "Автомобиль", "toolbox"));
            result.add(new LauncherIconResolver.Preset("fluent_wrench", "Ключ", "Автомобиль", "wrench"));
            result.add(new LauncherIconResolver.Preset("fluent_wrench_screwdriver", "Ключ отвёртка", "Автомобиль", "wrench screwdriver"));
            result.add(new LauncherIconResolver.Preset("fluent_shield_checkmark", "Защита готово", "Автомобиль", "shield checkmark"));
            result.add(new LauncherIconResolver.Preset("fluent_battery_charge", "Батарея зарядка", "Автомобиль", "battery charge"));
            result.add(new LauncherIconResolver.Preset("fluent_temperature", "Температура", "Автомобиль", "temperature"));
            result.add(new LauncherIconResolver.Preset("fluent_weather_snowflake", "Погода снег", "Автомобиль", "weather snowflake"));
            result.add(new LauncherIconResolver.Preset("fluent_home", "Дом", "Умный дом", "home"));
            result.add(new LauncherIconResolver.Preset("fluent_home_add", "Дом добавить", "Умный дом", "home add"));
            result.add(new LauncherIconResolver.Preset("fluent_home_garage", "Дом гараж", "Умный дом", "home garage"));
            result.add(new LauncherIconResolver.Preset("fluent_home_heart", "Дом сердце", "Умный дом", "home heart"));
            result.add(new LauncherIconResolver.Preset("fluent_home_person", "Дом человек", "Умный дом", "home person"));
            result.add(new LauncherIconResolver.Preset("fluent_home_more", "Дом ещё", "Умный дом", "home more"));
            result.add(new LauncherIconResolver.Preset("fluent_building_home", "Здание дом", "Умный дом", "building home"));
            result.add(new LauncherIconResolver.Preset("fluent_door", "Дверь", "Умный дом", "door"));
            result.add(new LauncherIconResolver.Preset("fluent_door_arrow_left", "Дверь стрелка влево", "Умный дом", "door arrow left"));
            result.add(new LauncherIconResolver.Preset("fluent_door_tag", "Дверь метка", "Умный дом", "door tag"));
            result.add(new LauncherIconResolver.Preset("fluent_lock_closed", "Замок закрыт", "Умный дом", "lock closed"));
            result.add(new LauncherIconResolver.Preset("fluent_lock_open", "Замок открыт", "Умный дом", "lock open"));
            result.add(new LauncherIconResolver.Preset("fluent_lightbulb", "Лампа", "Умный дом", "lightbulb"));
            result.add(new LauncherIconResolver.Preset("fluent_lightbulb_circle", "Лампа круг", "Умный дом", "lightbulb circle"));
            result.add(new LauncherIconResolver.Preset("fluent_lightbulb_pulse", "Лампа пульс", "Умный дом", "lightbulb pulse"));
            result.add(new LauncherIconResolver.Preset("fluent_plug_connected", "Розетка подключено", "Умный дом", "plug connected"));
            result.add(new LauncherIconResolver.Preset("fluent_plug_connected_settings", "Розетка подключено настройки", "Умный дом", "plug connected settings"));
            result.add(new LauncherIconResolver.Preset("fluent_plug_disconnected", "Розетка отключено", "Умный дом", "plug disconnected"));
            result.add(new LauncherIconResolver.Preset("fluent_power", "Питание", "Умный дом", "power"));
            result.add(new LauncherIconResolver.Preset("fluent_water", "Вода", "Умный дом", "water"));
            result.add(new LauncherIconResolver.Preset("fluent_drop", "Капля", "Умный дом", "drop"));
            result.add(new LauncherIconResolver.Preset("fluent_fire", "Огонь", "Умный дом", "fire"));
            result.add(new LauncherIconResolver.Preset("fluent_fireplace", "Камин", "Умный дом", "fireplace"));
            result.add(new LauncherIconResolver.Preset("fluent_camera_dome", "Камера купол", "Умный дом", "camera dome"));
            result.add(new LauncherIconResolver.Preset("fluent_wifi_1", "Wi‑Fi", "Умный дом", "wifi 1"));
            result.add(new LauncherIconResolver.Preset("fluent_wifi_2", "Wi‑Fi", "Умный дом", "wifi 2"));
            result.add(new LauncherIconResolver.Preset("fluent_wifi_3", "Wi‑Fi", "Умный дом", "wifi 3"));
            result.add(new LauncherIconResolver.Preset("fluent_wifi_4", "Wi‑Fi", "Умный дом", "wifi 4"));
            result.add(new LauncherIconResolver.Preset("fluent_router", "Роутер", "Умный дом", "router"));
            result.add(new LauncherIconResolver.Preset("fluent_router_off", "Роутер выключено", "Умный дом", "router off"));
            result.add(new LauncherIconResolver.Preset("fluent_bluetooth", "Bluetooth", "Умный дом", "bluetooth"));
            result.add(new LauncherIconResolver.Preset("fluent_bluetooth_connected", "Bluetooth подключено", "Умный дом", "bluetooth connected"));
            result.add(new LauncherIconResolver.Preset("fluent_bluetooth_disabled", "Bluetooth отключено", "Умный дом", "bluetooth disabled"));
            result.add(new LauncherIconResolver.Preset("fluent_battery_0", "Батарея", "Умный дом", "battery 0"));
            result.add(new LauncherIconResolver.Preset("fluent_battery_5", "Батарея", "Умный дом", "battery 5"));
            result.add(new LauncherIconResolver.Preset("fluent_battery_10", "Батарея", "Умный дом", "battery 10"));
            result.add(new LauncherIconResolver.Preset("fluent_clock_alarm", "Часы тревога", "Умный дом", "clock alarm"));
            result.add(new LauncherIconResolver.Preset("fluent_clock_warning", "Часы опасность", "Умный дом", "clock warning"));
            result.add(new LauncherIconResolver.Preset("fluent_presence_available", "Присутствие доступен", "Умный дом", "presence available"));
            result.add(new LauncherIconResolver.Preset("fluent_presence_away", "Присутствие нет дома", "Умный дом", "presence away"));
            result.add(new LauncherIconResolver.Preset("fluent_presence_busy", "Присутствие занят", "Умный дом", "presence busy"));
            result.add(new LauncherIconResolver.Preset("fluent_leaf_two", "Лист двойной", "Умный дом", "leaf two"));
            result.add(new LauncherIconResolver.Preset("fluent_animal_dog", "Животное собака", "Умный дом", "animal dog"));
            result.add(new LauncherIconResolver.Preset("fluent_weather_sunny", "Погода солнечно", "Умный дом", "weather sunny"));
            result.add(new LauncherIconResolver.Preset("fluent_weather_cloudy", "Погода облачно", "Умный дом", "weather cloudy"));
            result.add(new LauncherIconResolver.Preset("fluent_weather_rain", "Погода дождь", "Умный дом", "weather rain"));
            result.add(new LauncherIconResolver.Preset("fluent_weather_thunderstorm", "Погода гроза", "Умный дом", "weather thunderstorm"));
            result.add(new LauncherIconResolver.Preset("fluent_shield", "Защита", "Безопасность", "shield"));
            result.add(new LauncherIconResolver.Preset("fluent_shield_dismiss", "Защита закрыть", "Безопасность", "shield dismiss"));
            result.add(new LauncherIconResolver.Preset("fluent_shield_error", "Защита ошибка", "Безопасность", "shield error"));
            result.add(new LauncherIconResolver.Preset("fluent_shield_lock", "Защита замок", "Безопасность", "shield lock"));
            result.add(new LauncherIconResolver.Preset("fluent_shield_keyhole", "Защита скважина", "Безопасность", "shield keyhole"));
            result.add(new LauncherIconResolver.Preset("fluent_shield_prohibited", "Защита запрещено", "Безопасность", "shield prohibited"));
            result.add(new LauncherIconResolver.Preset("fluent_shield_question", "Защита вопрос", "Безопасность", "shield question"));
            result.add(new LauncherIconResolver.Preset("fluent_shield_settings", "Защита настройки", "Безопасность", "shield settings"));
            result.add(new LauncherIconResolver.Preset("fluent_shield_task", "Защита задача", "Безопасность", "shield task"));
            result.add(new LauncherIconResolver.Preset("fluent_lock_shield", "Замок защита", "Безопасность", "lock shield"));
            result.add(new LauncherIconResolver.Preset("fluent_key_multiple", "Ключ несколько", "Безопасность", "key multiple"));
            result.add(new LauncherIconResolver.Preset("fluent_alert", "Предупреждение", "Безопасность", "alert"));
            result.add(new LauncherIconResolver.Preset("fluent_alert_badge", "Предупреждение метка", "Безопасность", "alert badge"));
            result.add(new LauncherIconResolver.Preset("fluent_alert_off", "Предупреждение выключено", "Безопасность", "alert off"));
            result.add(new LauncherIconResolver.Preset("fluent_alert_on", "Предупреждение включено", "Безопасность", "alert on"));
            result.add(new LauncherIconResolver.Preset("fluent_alert_urgent", "Предупреждение срочно", "Безопасность", "alert urgent"));
            result.add(new LauncherIconResolver.Preset("fluent_info", "Информация", "Безопасность", "info"));
            result.add(new LauncherIconResolver.Preset("fluent_error_circle", "Ошибка круг", "Безопасность", "error circle"));
            result.add(new LauncherIconResolver.Preset("fluent_question_circle", "Вопрос круг", "Безопасность", "question circle"));
            result.add(new LauncherIconResolver.Preset("fluent_fingerprint", "Отпечаток", "Безопасность", "fingerprint"));
            result.add(new LauncherIconResolver.Preset("fluent_password", "Пароль", "Безопасность", "password"));
            result.add(new LauncherIconResolver.Preset("fluent_incognito", "Инкогнито", "Безопасность", "incognito"));
            result.add(new LauncherIconResolver.Preset("fluent_certificate", "Сертификат", "Безопасность", "certificate"));
            result.add(new LauncherIconResolver.Preset("fluent_scan_person", "Сканировать человек", "Безопасность", "scan person"));
            result.add(new LauncherIconResolver.Preset("fluent_flashlight", "Фонарь", "Безопасность", "flashlight"));
            result.add(new LauncherIconResolver.Preset("fluent_flashlight_off", "Фонарь выключено", "Безопасность", "flashlight off"));
            result.add(new LauncherIconResolver.Preset("fluent_cloud_checkmark", "Облако готово", "Безопасность", "cloud checkmark"));
            result.add(new LauncherIconResolver.Preset("fluent_cloud_error", "Облако ошибка", "Безопасность", "cloud error"));
            result.add(new LauncherIconResolver.Preset("fluent_person_warning", "Человек опасность", "Безопасность", "person warning"));
            result.add(new LauncherIconResolver.Preset("fluent_briefcase", "Портфель", "Работа и быт", "briefcase"));
            result.add(new LauncherIconResolver.Preset("fluent_briefcase_medical", "Портфель медицина", "Работа и быт", "briefcase medical"));
            result.add(new LauncherIconResolver.Preset("fluent_calculator", "Калькулятор", "Работа и быт", "calculator"));
            result.add(new LauncherIconResolver.Preset("fluent_document", "Документ", "Работа и быт", "document"));
            result.add(new LauncherIconResolver.Preset("fluent_document_add", "Документ добавить", "Работа и быт", "document add"));
            result.add(new LauncherIconResolver.Preset("fluent_document_edit", "Документ изменить", "Работа и быт", "document edit"));
            result.add(new LauncherIconResolver.Preset("fluent_document_save", "Документ сохранить", "Работа и быт", "document save"));
            result.add(new LauncherIconResolver.Preset("fluent_document_search", "Документ поиск", "Работа и быт", "document search"));
            result.add(new LauncherIconResolver.Preset("fluent_document_pdf", "Документ PDF", "Работа и быт", "document pdf"));
            result.add(new LauncherIconResolver.Preset("fluent_document_signature", "Документ подпись", "Работа и быт", "document signature"));
            result.add(new LauncherIconResolver.Preset("fluent_folder", "Папка", "Работа и быт", "folder"));
            result.add(new LauncherIconResolver.Preset("fluent_folder_open", "Папка открыт", "Работа и быт", "folder open"));
            result.add(new LauncherIconResolver.Preset("fluent_folder_add", "Папка добавить", "Работа и быт", "folder add"));
            result.add(new LauncherIconResolver.Preset("fluent_clipboard", "Буфер", "Работа и быт", "clipboard"));
            result.add(new LauncherIconResolver.Preset("fluent_clipboard_checkmark", "Буфер готово", "Работа и быт", "clipboard checkmark"));
            result.add(new LauncherIconResolver.Preset("fluent_clipboard_task", "Буфер задача", "Работа и быт", "clipboard task"));
            result.add(new LauncherIconResolver.Preset("fluent_code", "Код", "Работа и быт", "code"));
            result.add(new LauncherIconResolver.Preset("fluent_code_block", "Код блок", "Работа и быт", "code block"));
            result.add(new LauncherIconResolver.Preset("fluent_database", "База данных", "Работа и быт", "database"));
            result.add(new LauncherIconResolver.Preset("fluent_database_search", "База данных поиск", "Работа и быт", "database search"));
            result.add(new LauncherIconResolver.Preset("fluent_print", "Печать", "Работа и быт", "print"));
            result.add(new LauncherIconResolver.Preset("fluent_scan", "Сканировать", "Работа и быт", "scan"));
            result.add(new LauncherIconResolver.Preset("fluent_ruler", "Линейка", "Работа и быт", "ruler"));
            result.add(new LauncherIconResolver.Preset("fluent_compose", "Создать", "Работа и быт", "compose"));
            result.add(new LauncherIconResolver.Preset("fluent_organization", "Организация", "Работа и быт", "organization"));
            result.add(new LauncherIconResolver.Preset("fluent_building", "Здание", "Работа и быт", "building"));
            result.add(new LauncherIconResolver.Preset("fluent_building_bank", "Здание банк", "Работа и быт", "building bank"));
            result.add(new LauncherIconResolver.Preset("fluent_building_factory", "Здание завод", "Работа и быт", "building factory"));
            result.add(new LauncherIconResolver.Preset("fluent_building_shop", "Здание магазин", "Работа и быт", "building shop"));
            result.add(new LauncherIconResolver.Preset("fluent_cart", "Корзина", "Работа и быт", "cart"));
            result.add(new LauncherIconResolver.Preset("fluent_shopping_bag", "Покупки сумка", "Работа и быт", "shopping bag"));
            result.add(new LauncherIconResolver.Preset("fluent_wallet", "Кошелёк", "Работа и быт", "wallet"));
            result.add(new LauncherIconResolver.Preset("fluent_wallet_credit_card", "Кошелёк кредит карточка", "Работа и быт", "wallet credit card"));
            result.add(new LauncherIconResolver.Preset("fluent_payment", "Оплата", "Работа и быт", "payment"));
            result.add(new LauncherIconResolver.Preset("fluent_receipt", "Чек", "Работа и быт", "receipt"));
            result.add(new LauncherIconResolver.Preset("fluent_receipt_money", "Чек деньги", "Работа и быт", "receipt money"));
            result.add(new LauncherIconResolver.Preset("fluent_money", "Деньги", "Работа и быт", "money"));
            result.add(new LauncherIconResolver.Preset("fluent_money_hand", "Деньги рука", "Работа и быт", "money hand"));
            result.add(new LauncherIconResolver.Preset("fluent_gift", "Подарок", "Работа и быт", "gift"));
            result.add(new LauncherIconResolver.Preset("fluent_trophy", "Награда", "Работа и быт", "trophy"));
            result.add(new LauncherIconResolver.Preset("fluent_book", "Книга", "Работа и быт", "book"));
            result.add(new LauncherIconResolver.Preset("fluent_book_open", "Книга открыт", "Работа и быт", "book open"));
            result.add(new LauncherIconResolver.Preset("fluent_learning_app", "Обучение приложение", "Работа и быт", "learning app"));
            result.add(new LauncherIconResolver.Preset("fluent_pill", "Лекарство", "Работа и быт", "pill"));
            result.add(new LauncherIconResolver.Preset("fluent_food", "Еда", "Работа и быт", "food"));
            result.add(new LauncherIconResolver.Preset("fluent_food_apple", "Еда яблоко", "Работа и быт", "food apple"));
            result.add(new LauncherIconResolver.Preset("fluent_food_cake", "Еда торт", "Работа и быт", "food cake"));
            result.add(new LauncherIconResolver.Preset("fluent_food_pizza", "Еда пицца", "Работа и быт", "food pizza"));
        return Collections.unmodifiableList(result);
    }

    private static final class PresetHolder {
        @NonNull static final List<LauncherIconResolver.Preset> PRESETS = buildPresets();
    }
}
