plugins {
    id "com.android.application"
}

android {
    namespace "ru.natro.ancstest"
    compileSdk 35

    defaultConfig {
        applicationId "ru.natro.ancstest"
        minSdk 26
        targetSdk 28
        versionCode 8
        versionName "8.0"

        testInstrumentationRunner "android.test.InstrumentationTestRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lint {
        abortOnError true
        checkReleaseBuilds false
    }
}

dependencies {
    testImplementation "junit:junit:4.13.2"
}
