/* SPDX-License-Identifier: GPL-3.0-or-later */
package dezz.status.widget.automation;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.os.SystemClock;
import android.util.Log;

import androidx.annotation.Nullable;

import java.util.List;
import java.util.Map;

import dezz.status.widget.Preferences;
import dezz.status.widget.WidgetService;
import dezz.status.widget.integration.IntentScenarioController;
import dezz.status.widget.scenario.IntentActionRule;
import dezz.status.widget.scenario.IntentActionRuleStore;

/** Cold-start endpoint for user-configured, one-shot Intent rules. */
public final class ScenarioTriggerReceiver extends BroadcastReceiver {
    private static final String TAG = "ScenarioTrigger";

    /** Package-scoped cold-start action; saved rule id and token are both required. */
    public static final String ACTION_TRIGGER = "ru.natro.statuswidget.SCENARIO_TRIGGER";
    public static final String EXTRA_TRIGGER_ID = "trigger_id";
    /** Per-rule 128-bit secret shown by the editor and required by the fixed public endpoint. */
    public static final String EXTRA_TRIGGER_TOKEN = "trigger_token";
    /** Internal digest of the exact accepted rule; never supplied by the external sender. */
    public static final String EXTRA_RULE_FINGERPRINT = "rule_fingerprint";
    /** Internal absolute monotonic deadline captured when the external Broadcast arrives. */
    public static final String EXTRA_DEADLINE_ELAPSED = "deadline_elapsed";

    /** Internal explicit service action. WidgetService is not exported. */
    public static final String ACTION_EXECUTE_RULE =
            "ru.natro.statuswidget.internal.EXECUTE_INTENT_RULE";

    @Override public void onReceive(Context context, Intent intent) {
        // Include receiver lookup, process scheduling, and WidgetService.onCreate in the safety
        // window. Starting a new 15-second timer only after a slow cold start could execute a
        // physical command long after the steering press.
        final long deadlineElapsed = IntentScenarioController.deadlineAfter(
                SystemClock.elapsedRealtime());
        if (intent == null || !IntentScenarioController.isExplicitlyTargetedAt(
                intent, context.getPackageName())) {
            Log.w(TAG, "Ignored trigger that was not targeted at this package");
            return;
        }

        Preferences preferences = new Preferences(context);
        if (!preferences.widgetEnabled.get()) {
            Log.i(TAG, "Ignored trigger while the widget service is disabled");
            return;
        }

        final IntentActionRule rule;
        try {
            List<IntentActionRule> rules = new IntentActionRuleStore(preferences).loadStrict();
            if (ACTION_TRIGGER.equals(intent.getAction())) {
                // A predictable rule id is not authentication. The fixed exported endpoint
                // requires both the id and the random per-rule token generated by the editor.
                rule = enabledByIdAndToken(rules,
                        stringExtra(intent, EXTRA_TRIGGER_ID),
                        stringExtra(intent, EXTRA_TRIGGER_TOKEN));
            } else {
                // An arbitrary action reaches a stopped process only when the sender explicitly
                // addresses this receiver class. The exact saved allowlist is still authoritative.
                Map<String, IntentActionRule> byAction =
                        IntentActionRuleStore.enabledByAction(rules);
                rule = intent.getAction() == null ? null : byAction.get(intent.getAction());
            }
        } catch (IllegalArgumentException invalid) {
            Log.w(TAG, "Ignored trigger because Intent rule settings are invalid", invalid);
            return;
        }
        if (rule == null) {
            Log.w(TAG, "Ignored unknown or disabled Intent trigger");
            return;
        }

        Intent service = new Intent(context, WidgetService.class)
                .setAction(ACTION_EXECUTE_RULE)
                .putExtra(EXTRA_TRIGGER_ID, rule.id)
                // Also fingerprint the exact rule accepted above. The service reloads settings
                // and refuses the command if this id was edited/reused before it starts.
                .putExtra(EXTRA_TRIGGER_TOKEN, rule.triggerToken)
                .putExtra(EXTRA_RULE_FINGERPRINT, rule.executionFingerprint())
                .putExtra(EXTRA_DEADLINE_ELAPSED, deadlineElapsed);
        try {
            context.startForegroundService(service);
        } catch (RuntimeException failure) {
            // No durable command is intentionally retained: retrying a TOGGLE after an ambiguous
            // process/system failure could reverse an already-applied physical action.
            Log.e(TAG, "Could not start foreground service for Intent rule " + rule.id, failure);
        }
    }

    @Nullable
    static IntentActionRule enabledByIdAndToken(List<IntentActionRule> rules,
                                                @Nullable String rawId,
                                                @Nullable String rawToken) {
        String id = rawId == null ? "" : rawId.trim();
        String token = rawToken == null ? "" : rawToken.trim().toLowerCase(java.util.Locale.ROOT);
        if (id.isEmpty() || id.length() > 128 || token.length() != 32) return null;
        for (IntentActionRule rule : rules) {
            if (rule.enabled && rule.id.equals(id) && rule.matchesTriggerToken(token)) {
                return rule;
            }
        }
        return null;
    }

    @Nullable
    private static String stringExtra(Intent intent, String name) {
        try {
            return intent.getStringExtra(name);
        } catch (RuntimeException wrongType) {
            return null;
        }
    }
}
